### PR TITLE
Jruby 9k 

### PR DESCRIPTION
**Pull request by mkristian**
Prep jruby-9k and reduce size of overall plugins

### CODE REVIEW

**Comment by deivid-rodriguez** [comment]
@mkristian I hadn't noticed this PR. I've been working on this same thing at https://github.com/torquebox/jruby-maven-plugins/pull/119. Everything is green now on java 11, and jruby 9.2. I dropped support for stuff older than that, because IMO opinion this repo seems virtually unmaintained so we should aim just for the latest stable versions. Still need to fix some stuff that I skipped, but it's looking good I believe.

**Comment by mkristian** [comment]
@deivid-rodriguez yes, I just saw you PR

never mind. in the end I wanted to drop a few things. maybe I just pick your branch and drop what I wanted to drop ? I mean make small PRs against your branch . . .

**Comment by deivid-rodriguez** [comment]
The branch is not really ready. I think maybe better if you first drop what you want to drop, then I can rebase this to fix the rest of the stuff.

**Comment by mkristian** [comment]
ok - I make a `version-2` branch and drop things, and bump to 2.0.0-SNAPSHOT 

next I wanted to replace all these `http://rubygems-proxy.torquebox.org/` with mavengems wagon at least in the integration tests.

**Comment by deivid-rodriguez** [comment]
Sure. Why not master though, if I may ask?

**Comment by mkristian** [comment]
habit - but I can do it on master. np

**Comment by mkristian** [comment]
@deivid-rodriguez any ways merge this branch to master now

**Comment by deivid-rodriguez** [comment]
Awesome thanks! I'll rebase this on top of your changes and get it ready :+1:.

**Comment by headius** [comment]
I'm not sure whether this is still relevant. In #126 I have continued to migrate to latest JRuby plus latest mavengem, as part of an overall push to update the JRuby/Maven stack (but also to address the v1/dependencies shutdown).

**Comment by headius** [comment]
The update to JRuby 9k happened long ago, and in #126 I updated JRuby to 9.4.3.0, but there are other parts here that could be re-applied in 3.0.1.

**Pull request closed without merging**
